### ISSUE TITLE
Filter designer fails

### ISSUE THREAD

**Issue by rgetz** [analogdevicesinc/ad936x-filter-wizard#12]
When setting all the half bands to decimate/interpolate by 1,

![image](https://cloud.githubusercontent.com/assets/1017869/17802787/45a6df26-65c0-11e6-91e1-3ced716f09c1.png)

 the design function fails with:

> > AD9361_Filter_Wizard
> > Undefined function 'cascade' for input arguments of type 'double'.

Error in internal_design_filter (line 265)
dfilter = cascade(filter_stages{:});

Error in AD9361_Filter_Wizard>create_filter (line 1107)
filter_result = internal_design_filter(filter_input);

Error in AD9361_Filter_Wizard>design_filter_Callback (line 2705)
create_filter(hObject, handles);

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in AD9361_Filter_Wizard (line 96)
    gui_mainfcn(gui_State, varargin{:});

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)AD9361_Filter_Wizard('design_filter_Callback',hObject,eventdata,guidata(hObject)) 
Error using uiwait (line 81)
Error while evaluating UIControl Callback

Operation terminated by user during uiwait (line 81)

In AD9361_Filter_Wizard>AD9361_Filter_Wizard_OpeningFcn (line 250)
uiwait(handles.AD9361_Filter_app);

In gui_mainfcn (line 220)
    feval(gui_State.gui_OpeningFcn, gui_hFigure, [], guidata(gui_hFigure), varargin{:});

In AD9361_Filter_Wizard (line 96)
    gui_mainfcn(gui_State, varargin{:});

and the GUI hangs.

-Robin

**Comment by rgetz** [comment]
I don't know if this still happens?

**Comment by tfcollins** [comment]
You get a warning from the designer that a filter cannot be designed for this configuration.  Code change came here: https://github.com/analogdevicesinc/ad936x-filter-wizard/commit/93aa9f0fd1a2620331f88919b3df85b0f77740bb

**Comment by rgetz** [comment]
Thanks for checking.
