### ISSUE TITLE
Filter designer fails

### ISSUE THREAD

**Issue by kasraghu** [analogdevicesinc/ad936x-filter-wizard#14]
When setting HBs factor as 2,

![image](https://cloud.githubusercontent.com/assets/9320689/18266168/a547e738-7419-11e6-8697-31caca619a0f.png)
the design function fails with:

> Error using dsp.FilterCascade/checkStageType (line 405)
Invalid stage - dsp.FilterCascade cannot be used as a stage of another cascade.
Error in dsp.FilterCascade/addStage (line 149)
            checkStageType(obj, stage);
Error in dsp.FilterCascade (line 122)
                        addStage(obj, varargin{ind});
Error in dsp.private.FilterAnalysis/cascade (line 1351)
        FC = dsp.FilterCascade(obj,varargin{:});
Error in internal_design_filter (line 270)
        Hmiddle = cascade(Hd1,Hmiddle);
Error in AD9361_Filter_Wizard>create_filter (line 1106)
filter_result = internal_design_filter(filter_input);
Error in AD9361_Filter_Wizard>design_filter_Callback (line 2664)
create_filter(hObject, handles);
Error in gui_mainfcn (line 95)
        feval(varargin{:});
Error in AD9361_Filter_Wizard (line 97)
    gui_mainfcn(gui_State, varargin{:});
Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)AD9361_Filter_Wizard('design_filter_Callback',hObject,eventdata,guidata(hObject)) 
Error using uiwait (line 81)
Error while evaluating UIControl Callback

**Comment by dpu1778** [comment]
I have tried out your settings on my end, did not get the errors. Filters can be designed. Please make sure you are using MATLAB 2016a and later and your filter wizard version is the latest.
![filter](https://cloud.githubusercontent.com/assets/4982885/18276658/b3bdac58-7419-11e6-92d8-c9f48abf642b.png)

**Comment by kasraghu** [comment]
Hi,
You can see from my screenshot that I have the latest 16.1.1 version running.
In your screenshot, the version number seems to have an extension. Is it the same version available at following link?
[https://github.com/analogdevicesinc/ad936x-filter-wizard/releases](url) 

I am using Matlab2016a.

**Comment by dpu1778** [comment]
Hi, I am using the filter wizard from 2016_R1 branch: https://github.com/analogdevicesinc/ad936x-filter-wizard/tree/2016_R1
It is possible that some of the changes in this branch are ahead of the major releases.

**Comment by kasraghu** [comment]
Thank you. I downloaded the files from the branch and am able to design the filter.
