### ISSUE TITLE
AD9361_Filter_Wizard>save2HDL_Callback

### ISSUE THREAD

**Issue by yundebian** [analogdevicesinc/ad936x-filter-wizard#15]
hi：
i  decide to have the FIR filter implemented on FPGA，but when clicking “Generate HDL”,it appears some erro.

erro AD9361_Filter_Wizard>save2HDL_Callback (line 2265)
    Hd = handles.filter.Stage(2);

erro gui_mainfcn (line 95)
        feval(varargin{:});

erro AD9361_Filter_Wizard (line 97)
    gui_mainfcn(gui_State, varargin{:});

erro
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)AD9361_Filter_Wizard('save2HDL_Callback',hObject,eventdata,guidata(hObject))

**Comment by dpu1778** [comment]
Hi, thanks for letting us know. The save2HDL function has been changed in this commit: https://github.com/analogdevicesinc/ad936x-filter-wizard/commit/a6c804197bd04fdebb769ee62c1f5a734bb75863
Please get the latest version from master branch and try it out.

**Comment by radhermit** [comment]
Fixed in the 16.1.3 release.
