### ISSUE TITLE
Generate HDL button does not show up in GUI

### ISSUE THREAD

**Issue by dpu1778** [analogdevicesinc/ad936x-filter-wizard#16]
When I was fixing the save2HDL function today, I found the “Generate HDL” button does not show up in the GUI after a filter is designed. This button used to show up under the “Design Filter” button in order versions. It is still there in the .fig file, so I think some callback functions need to be changed.

![hdl](https://cloud.githubusercontent.com/assets/4982885/19246100/a96a5bf4-8ef2-11e6-98d1-b591c15f7453.png)

**Comment by radhermit** [comment]
The button only shows up if the "Use Internal FIR" toggle box is disabled. I think this is still working as expected and discussed.
